import Head from 'next/head';

export default function CommonHeader() {
    return (
        <Head>
            <title>Recipes</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}